// Command gen bundles the vendored SheetJS (xlsx.full.min.js) with each Excel
// drop body into a single self-contained drop source under officialdrops/, which
// officialdrops embeds and compiles. Run from the officialdrops/ directory:
//
//	go generate ./officialdrops
//
// SheetJS is wrapped in an IIFE that hands it a LOCAL `exports` (the
// require('xlsx') path) and returns it as `const XLSX`, so the drop's own
// `export default` is untouched. Runs on the Node drop host.
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const header = "// Code generated by officialdrops/excelsrc/gen.go — DO NOT EDIT.\n" +
	"// Bundles the vendored SheetJS (excelsrc/xlsx.full.min.js) ahead of the drop\n" +
	"// body (excelsrc/<name>.body.ts). Edit those + re-run `go generate ./officialdrops`.\n\n"

func main() {
	sheet, err := os.ReadFile("excelsrc/xlsx.full.min.js")
	if err != nil {
		fmt.Fprintln(os.Stderr, "read SheetJS:", err)
		os.Exit(1)
	}
	for _, name := range []string{"excel_read", "excel_write"} {
		body, err := os.ReadFile(filepath.Join("excelsrc", name+".body.ts"))
		if err != nil {
			fmt.Fprintln(os.Stderr, "read body:", err)
			os.Exit(1)
		}
		var b []byte
		b = append(b, header...)
		b = append(b, "const XLSX: any = (function () { var exports: any = {};\n"...)
		b = append(b, sheet...)
		b = append(b, "\nreturn exports; })();\n\n"...)
		b = append(b, body...)
		out := name + ".ts"
		if err := os.WriteFile(out, b, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "write:", err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s (%d bytes)\n", out, len(b))
	}
}
