// SPDX-FileCopyrightText: 2026 Angels' Ware
// SPDX-License-Identifier: AGPL-3.0-or-later

package pdf

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/dazyflow/dazyflow/core"
	"github.com/dazyflow/dazyflow/drops/internal/sandbox"
)

// makePDF builds a minimal but genuinely valid PDF with n empty pages, xref
// offsets included.
//
// Hand-built rather than generated by a library: a test PDF is a fixture, and
// a fixture produced by the same library under test proves less than one
// assembled from the format's own rules. It also keeps a PDF *writer* out of
// the dependency list for the sake of tests.
func makePDF(t *testing.T, n int) []byte {
	t.Helper()
	if n < 1 {
		t.Fatalf("makePDF needs at least one page, got %d", n)
	}

	// Object 1 is the catalog, 2 the page tree, 3..n+2 the pages.
	kids := ""
	for i := range n {
		kids += fmt.Sprintf("%d 0 R ", i+3)
	}
	objects := []string{
		"<< /Type /Catalog /Pages 2 0 R >>",
		fmt.Sprintf("<< /Type /Pages /Kids [%s] /Count %d >>", kids, n),
	}
	for range n {
		// A page with no /Contents is a legal empty page.
		objects = append(objects, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] >>")
	}

	var buf bytes.Buffer
	buf.WriteString("%PDF-1.4\n")
	offsets := make([]int, len(objects)+1) // 1-indexed by object number
	for i, body := range objects {
		offsets[i+1] = buf.Len()
		fmt.Fprintf(&buf, "%d 0 obj\n%s\nendobj\n", i+1, body)
	}

	xrefAt := buf.Len()
	fmt.Fprintf(&buf, "xref\n0 %d\n", len(objects)+1)
	// The free-list head, then one 20-byte entry per object — the trailing
	// space matters: every entry is exactly 20 bytes or the table is invalid.
	buf.WriteString("0000000000 65535 f \n")
	for i := 1; i <= len(objects); i++ {
		fmt.Fprintf(&buf, "%010d 00000 n \n", offsets[i])
	}
	fmt.Fprintf(&buf, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objects)+1, xrefAt)
	return buf.Bytes()
}

// pdfJob wires a file into a job the way the engine does, with somewhere to
// write.
func pdfJob(t *testing.T, files map[string][]byte, port string, order ...string) core.Job {
	t.Helper()
	root := t.TempDir()
	ws := filepath.Join(root, "ws")
	scratch := filepath.Join(root, "scratch")
	for _, d := range []string{ws, scratch} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	job := core.Job{
		ID: "j", GraphID: "g", NodeID: "n", Tenant: "t",
		WorkspaceRoot: ws, ScratchRoot: scratch,
		Input: map[string]core.Ref{},
	}
	for i, name := range order {
		if err := os.WriteFile(filepath.Join(ws, name), files[name], 0o644); err != nil {
			t.Fatal(err)
		}
		key := port
		if len(order) > 1 || port == "files" {
			key = fmt.Sprintf("%s[%d]", port, i)
		}
		job.Input[key] = core.Ref{Ref: name, MIME: "application/pdf"}
	}
	return job
}

// readOut reads a file a drop produced, from wherever it put it.
func readOut(t *testing.T, job core.Job, dest string) []byte {
	t.Helper()
	root, rel, err := sandbox.Resolve(job, dest)
	if err != nil {
		t.Fatalf("resolve %q: %v", dest, err)
	}
	b, rerr := os.ReadFile(filepath.Join(root, rel))
	if rerr != nil {
		t.Fatalf("read %q: %v", dest, rerr)
	}
	return b
}

// The fixture has to be a PDF pdfcpu itself accepts, or every test below is
// testing the fixture rather than the drop.
func TestMakePDF_IsValid(t *testing.T) {
	for _, n := range []int{1, 3, 10} {
		job := pdfJob(t, map[string][]byte{"in.pdf": makePDF(t, n)}, "file", "in.pdf")
		res, err := executePDFInfo(t.Context(), job, nil)
		if err != nil {
			t.Fatalf("execute: %v", err)
		}
		if res.Status != core.StatusOK {
			t.Fatalf("%d-page fixture rejected: %+v", n, res.Error)
		}
		if got, _ := res.Output["pages"].Inline.(string); got != fmt.Sprint(n) {
			t.Errorf("pages = %q, want %d", got, n)
		}
	}
}
