// SPDX-FileCopyrightText: 2026 Angels' Ware
// SPDX-License-Identifier: AGPL-3.0-or-later

// Structural guards on the guide.
//
// A guide page has two halves that are written in different places: the
// markdown in docs/guide/, and a row in NAV below. Miss the second and the page
// is unreachable — no build fails, no link 404s, the page simply isn't there.
// That is how members, roles and approvals went undocumented while being
// primary UI, so it's worth a test rather than a habit.
//
// These assert against docs/guide/ (committed) rather than
// web/src/docs/content/ (generated by `make docs-content`, git-ignored, and
// NOT present when CI runs `npm test` — the docs task comes after). The few
// checks that need the rendered bundle skip when it hasn't been generated.

import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { NAV, ORDER, getPage, neighbours } from "./content";

const GUIDE_SRC = join(__dirname, "../../../docs/guide");
const BUNDLE = join(__dirname, "content/guide");

const guideSlugs = () =>
  readdirSync(GUIDE_SRC)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""))
    .sort();

const navGuideLinks = () =>
  NAV.flatMap((g) => g.items)
    .map((i) => i.link)
    .filter((l) => l.startsWith("/guide/"));

const readGuide = (slug: string) =>
  readFileSync(join(GUIDE_SRC, `${slug}.md`), "utf8");

describe("guide structure", () => {
  it("gives every guide page a sidebar row, and every row a page", () => {
    const fromDisk = guideSlugs();
    const fromNav = navGuideLinks()
      .map((l) => l.replace("/guide/", ""))
      .sort();
    expect(fromNav).toEqual(fromDisk);
  });

  it("puts every sidebar row in the reading order", () => {
    for (const link of navGuideLinks()) {
      expect(ORDER.some((p) => p.link === link)).toBe(true);
    }
  });
});

describe("teams & approvals guide", () => {
  // The page that documents members, roles and approvals. Its absence is what
  // made a cold walkthrough guess at all three.
  const body = readGuide("teams-and-approvals");

  it("names all three roles and what sets them apart", () => {
    for (const role of ["Viewer", "Editor", "Admin"]) {
      expect(body).toContain(`**${role}**`);
    }
    // The non-obvious one, and the reason the page exists: approving does not
    // need edit access, so an approver can hold the least-privileged role.
    expect(body).toMatch(/Viewer[\s\S]{0,200}approve/i);
  });

  it("covers the invite path end to end", () => {
    expect(body).toContain("Admin → People");
    expect(body).toContain("Copy link"); // works without a mailer
    expect(body).toContain("14 days"); // invitations expire
  });

  it("explains that outstanding invitations hold a seat", () => {
    expect(body).toMatch(/invitation[\s\S]{0,120}seat/i);
  });

  it("tells the reader to wire the value being decided into the step", () => {
    expect(body).toContain("Wait for approval");
    expect(body).toContain("`Value`");
    expect(body).toContain("`Approved`");
    // The link is the permission — worth knowing before you forward one.
    expect(body).toMatch(/anyone holding the approval link/i);
  });
});

describe("glossary", () => {
  const body = readGuide("glossary");

  it("defines the words the teams page leans on", () => {
    for (const term of [
      "Approval",
      "Invitation",
      "Member",
      "Organization",
      "Role",
      "Seat",
    ]) {
      expect(body).toContain(`### ${term}`);
    }
  });

  it("keeps its entries in alphabetical order", () => {
    // The whole value of a glossary is that a reader can find the word.
    const headings = [...body.matchAll(/^### (.+)$/gm)].map((m) =>
      m[1].toLowerCase(),
    );
    expect(headings).toEqual([...headings].sort());
  });
});

// These need `make docs-content` to have run. Skipped rather than failed when
// it hasn't, so the suite stays green on a clean checkout.
describe.skipIf(!existsSync(BUNDLE))("rendered bundle", () => {
  it("ships every guide page", () => {
    const shipped = readdirSync(BUNDLE)
      .filter((f) => f.endsWith(".md"))
      .map((f) => f.replace(/\.md$/, ""))
      .sort();
    expect(shipped).toEqual(guideSlugs());
  });

  it("resolves every sidebar link to a real page", () => {
    const missing = NAV.flatMap((g) => g.items)
      .map((i) => i.link)
      .filter((link) => !getPage(link));
    expect(missing).toEqual([]);
  });

  it("places teams & approvals between forms and failures", () => {
    expect(getPage("/guide/teams-and-approvals")?.title).toBe(
      "Teams & approvals",
    );
    const { prev, next } = neighbours("/guide/teams-and-approvals");
    expect(prev?.link).toBe("/guide/forms-and-webhooks");
    expect(next?.link).toBe("/guide/when-a-flow-fails");
  });
});
