// SPDX-FileCopyrightText: 2026 Joachim Klahr
// SPDX-License-Identifier: AGPL-3.0-or-later

// Importing operations from an OpenAPI spec — the second front end onto the
// same descriptor the form below it builds by hand.
//
// The feature is "import OPERATIONS", never "register a spec", and that shows
// here more than anywhere: reading a document produces a LIST, and nothing is
// stored until the admin has chosen from it and pressed the form's own Save.
// Stripe's spec is ~500 operations and GitHub's ~900; registering one naively
// would file every one of them into the palette and into the flow generator's
// grounding, which is not "slow", it is unusable.
//
// Refresh is the same panel pointed at a catalog that already exists. The
// difference that matters is removals: an operation can vanish from a spec
// because someone deleted a handler, and the steps it contributed are
// referenced by saved flows. So a refresh reports what it would take away and
// will not do it until the admin says so.
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { AlertTriangle, Minus, Plus, RefreshCw } from "lucide-react";
import { Button } from "../ui/Button";
import { Callout } from "../ui/Callout";
import { ErrorNotice } from "../ui/ErrorNotice";
import { ICON } from "../../icons";
import { api } from "../../api";
import { useAuth } from "../../auth";
import { explainApiError } from "../../lib/explainApiError";
import type {
  WebAPIOperation,
  WebAPISpecResponse,
  WebAPIRefreshDiff,
} from "../../types";

// SpecSource is where the document comes from. A URL is fetched by the daemon
// through its guarded caller; a paste covers the API whose spec the daemon
// cannot reach (behind a VPN, on a laptop, generated locally).
type SpecSource = "url" | "paste";

export function WebAPISpecImport({
  againstName,
  storedSpecURL,
  onImport,
}: {
  // againstName names an existing catalog, which turns this into a refresh:
  // the daemon diffs and the removals need confirming.
  againstName?: string;
  storedSpecURL?: string;
  // onImport hands the chosen operations to the form, which is what actually
  // saves them. This component never writes.
  onImport: (result: {
    operations: WebAPIOperation[];
    title?: string;
    baseURL?: string;
    specURL?: string;
  }) => void;
}) {
  const { t } = useTranslation();
  const { token } = useAuth();
  const [source, setSource] = useState<SpecSource>(storedSpecURL ? "url" : "url");
  const [url, setURL] = useState(storedSpecURL ?? "");
  const [pasted, setPasted] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const [result, setResult] = useState<WebAPISpecResponse | null>(null);
  const [chosen, setChosen] = useState<Set<string>>(new Set());
  // Removals are opt-in, every time. Not remembered across reads: a fresh
  // document is a fresh decision.
  const [confirmRemovals, setConfirmRemovals] = useState(false);

  const read = async () => {
    if (!token) return;
    setBusy(true);
    setError(null);
    try {
      const res = await api.parseWebAPISpec(token, {
        url: source === "url" ? url.trim() : undefined,
        spec: source === "paste" ? pasted : undefined,
        against: againstName,
      });
      setResult(res);
      setConfirmRemovals(false);
      // Everything is selected on a first import — the common case is a small
      // in-house spec where all of it is wanted — but never more than the cap,
      // so pressing Import cannot produce a save the daemon refuses.
      const ids = res.operations.slice(0, res.max).map((op) => op.id);
      setChosen(new Set(ids));
    } catch (e) {
      setError(e);
      setResult(null);
    } finally {
      setBusy(false);
    }
  };

  const toggle = (id: string) =>
    setChosen((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const selectByTag = (tag: string) => {
    if (!result) return;
    const tagged = result.operation_tags ?? {};
    setChosen(
      new Set(
        result.operations
          .filter((op) => (tagged[op.id] ?? []).includes(tag))
          .slice(0, result.max)
          .map((op) => op.id),
      ),
    );
  };

  const removals = result?.diff ? removedFrom(result.diff) : [];
  const blockedOnConfirm = removals.length > 0 && !confirmRemovals;
  const overCap = !!result && chosen.size > result.max;

  const doImport = () => {
    if (!result) return;
    const picked = result.operations.filter((op) => chosen.has(op.id));
    // On a refresh, an operation the admin did NOT confirm removing is kept:
    // an unconfirmed refresh is strictly additive, so a spec regenerated by a
    // vendor's build pipeline can never cost a flow its steps.
    onImport({
      operations: picked,
      title: result.title,
      baseURL: result.base_url,
      specURL: source === "url" ? url.trim() : undefined,
    });
  };

  return (
    <div className="card wa-import">
      <h3>{againstName ? t("webapi.refreshTitle") : t("webapi.importTitle")}</h3>
      <div className="desc">{t("webapi.importHint")}</div>

      <div className="sf-field">
        <label htmlFor="wa-spec-source">{t("webapi.specSourceLabel")}</label>
        <select
          id="wa-spec-source"
          value={source}
          onChange={(e) => setSource(e.target.value as SpecSource)}
        >
          <option value="url">{t("webapi.specSourceURL")}</option>
          <option value="paste">{t("webapi.specSourcePaste")}</option>
        </select>
      </div>

      {source === "url" ? (
        <div className="sf-field">
          <label htmlFor="wa-spec-url">{t("webapi.specURLLabel")}</label>
          <input
            id="wa-spec-url"
            value={url}
            onChange={(e) => setURL(e.target.value)}
            placeholder="https://api.example.com/openapi.json"
          />
          <div className="desc">{t("webapi.specURLHint")}</div>
        </div>
      ) : (
        <div className="sf-field">
          <label htmlFor="wa-spec-paste">{t("webapi.specPasteLabel")}</label>
          <textarea
            id="wa-spec-paste"
            className="wa-spec-paste"
            value={pasted}
            onChange={(e) => setPasted(e.target.value)}
            rows={8}
            placeholder="openapi: 3.0.0"
          />
        </div>
      )}

      <Button
        variant="secondary"
        icon={<RefreshCw size={ICON.sm} />}
        onClick={read}
        disabled={busy || (source === "url" ? !url.trim() : !pasted.trim())}
      >
        {busy ? t("webapi.specReading") : t("webapi.specRead")}
      </Button>

      {error != null && <ErrorNotice>{explainApiError(error, t)}</ErrorNotice>}

      {result && (
        <div className="wa-import-result">
          {/* Warnings are things NOT imported. Shown before the list, because
              they explain why an operation the admin expected is missing. */}
          {(result.warnings ?? []).length > 0 && (
            <Callout variant="warning">
              <strong>{t("webapi.specWarnings", { count: result.warnings!.length })}</strong>
              <ul>
                {result.warnings!.map((w, i) => (
                  <li key={i}>
                    {w.where ? <code>{w.where}</code> : null} {w.reason}
                  </li>
                ))}
              </ul>
            </Callout>
          )}

          {result.overflow && (
            <Callout variant="warning">
              {t("webapi.specOverflow", {
                count: result.operations.length,
                max: result.max,
              })}
            </Callout>
          )}

          {result.diff && <RefreshSummary diff={result.diff} />}

          {removals.length > 0 && (
            <Callout variant="danger">
              <strong>{t("webapi.specRemovalsTitle", { count: removals.length })}</strong>
              <ul>
                {removals.map((op) => (
                  <li key={op.id}>
                    <code>{op.step_id}</code>
                  </li>
                ))}
              </ul>
              <label className="wa-confirm">
                <input
                  type="checkbox"
                  checked={confirmRemovals}
                  onChange={(e) => setConfirmRemovals(e.target.checked)}
                />
                {t("webapi.specConfirmRemovals")}
              </label>
            </Callout>
          )}

          {(result.tags ?? []).length > 0 && (
            <div className="wa-tag-filters">
              <span className="desc">{t("webapi.specByTag")}</span>
              {result.tags!.map((tag) => (
                <Button key={tag} variant="ghost" size="sm" onClick={() => selectByTag(tag)}>
                  {tag}
                </Button>
              ))}
            </div>
          )}

          <div className="wa-op-picker">
            {result.operations.map((op) => (
              <label key={op.id} className="wa-op-row">
                <input
                  type="checkbox"
                  checked={chosen.has(op.id)}
                  onChange={() => toggle(op.id)}
                />
                <span className="wa-op-method">{op.method}</span>
                <code className="wa-op-path">{op.path}</code>
                <span className="wa-op-title">{op.title || op.id}</span>
              </label>
            ))}
          </div>

          {overCap && (
            <Callout variant="warning">
              {t("webapi.specTooMany", { count: chosen.size, max: result.max })}
            </Callout>
          )}

          <Button onClick={doImport} disabled={chosen.size === 0 || blockedOnConfirm || overCap}>
            {t("webapi.specImport", { count: chosen.size })}
          </Button>
        </div>
      )}
    </div>
  );
}

function removedFrom(diff: WebAPIRefreshDiff) {
  return diff.operations.filter((op) => op.change === "removed");
}

// RefreshSummary is the counts line: what a re-import would do, before the
// detail. Reported in full — including "unchanged" — so the reader does not
// have to subtract to work out whether anything happened.
function RefreshSummary({ diff }: { diff: WebAPIRefreshDiff }) {
  const { t } = useTranslation();
  return (
    <div className="wa-diff-summary">
      <span className="wa-diff-added">
        <Plus size={ICON.xs} />
        {t("webapi.diffAdded", { count: diff.added })}
      </span>
      <span className="wa-diff-changed">
        <RefreshCw size={ICON.xs} />
        {t("webapi.diffChanged", { count: diff.changed })}
      </span>
      <span className="wa-diff-removed">
        <Minus size={ICON.xs} />
        {t("webapi.diffRemoved", { count: diff.removed })}
      </span>
      <span className="wa-diff-unchanged">
        {t("webapi.diffUnchanged", { count: diff.unchanged })}
      </span>
      {diff.removed > 0 && (
        <span className="wa-diff-warn">
          <AlertTriangle size={ICON.xs} />
        </span>
      )}
    </div>
  );
}
