import { defineConfig } from 'vitepress'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// The Step-catalog reference (docs/reference/steps/) is GENERATED by
// `make docs-reference` from the drop manifests and is git-ignored, so we build
// its sidebar dynamically at config time by reading each page's front-matter
// `title`. If the reference hasn't been generated yet, we degrade to just the
// catalog index so `vitepress build` still succeeds.
const here = path.dirname(fileURLToPath(import.meta.url))
const referenceDir = path.resolve(here, '../reference/steps')

function referenceSidebar() {
  let files: string[] = []
  try {
    files = fs.readdirSync(referenceDir).filter((f) => f.endsWith('.md') && f !== 'index.md')
  } catch {
    return [{ text: 'All steps', link: '/reference/steps/' }]
  }
  const groups = files.map((file) => {
    const src = fs.readFileSync(path.join(referenceDir, file), 'utf8')
    const m = src.match(/^title:\s*(.+)$/m)
    const text = (m ? m[1] : file.replace(/\.md$/, '')).trim()
    return { text, link: `/reference/steps/${file.replace(/\.md$/, '')}` }
  })
  groups.sort((a, b) => a.text.localeCompare(b.text))
  return [
    { text: 'All steps', link: '/reference/steps/' },
    { text: 'By group', collapsed: false, items: groups },
  ]
}

export default defineConfig({
  title: 'Dazyflow Docs',
  description:
    'Build automations without code — connect your apps and let the repetitive work run itself.',
  cleanUrls: true,
  lastUpdated: true,

  // Operator/legal docs live alongside the user guide in docs/ but are not part
  // of the public docs site.
  srcExclude: ['DEPLOY.md', 'COMPLIANCE.md', 'PRIVACY.md', 'SECURITY-SLA.md', 'TODO.md', 'README.md'],

  // The generated reference links to /guide/* and /reference/steps/*; when the
  // reference tree hasn't been generated those resolve at build time on the
  // deploy host. Keep the build resilient rather than failing on a missing page.
  ignoreDeadLinks: true,

  themeConfig: {
    nav: [
      { text: 'Concepts', link: '/guide/concepts' },
      { text: 'Glossary', link: '/guide/glossary' },
      { text: 'Step catalog', link: '/reference/steps/' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'How Dazyflow works', link: '/guide/concepts' },
            { text: 'Glossary', link: '/guide/glossary' },
          ],
        },
      ],
      '/reference/': [{ text: 'Step catalog', items: referenceSidebar() }],
    },
    search: { provider: 'local' },
    outline: 'deep',
  },
})
