// SPDX-FileCopyrightText: 2026 Angels' Ware
// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build ignore

// Prints the Swedish → English search vocabulary as a TypeScript module, from
// the Go table in internal/svsearch that both search paths read.
//
// The table used to live in web/src/lib/dropSearch.ts, which split the product
// in two: a Swedish word added so a person could find a step in the editor's
// palette did nothing for the same person asking the AI to build the flow,
// because the server-side search — the one search_drops and the MCP
// list_drops tool go through — had never heard of it. Go owns the data now and
// the web reads a generated copy.
//
// TypeScript rather than the JSON the other two scripts emit: those are read
// by guard tests, this one is imported by application code, so it carries its
// own types and needs no tsconfig change to consume.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/dazyflow/dazyflow/internal/svsearch"
)

func main() {
	var b strings.Builder
	b.WriteString("// SPDX-FileCopyrightText: 2026 Angels' Ware\n")
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later\n\n")
	b.WriteString("// GENERATED by scripts/svaliases.go from internal/svsearch — do not edit.\n")
	b.WriteString("// Run `make sv-aliases` after changing the Go table; `make catalogs-check`\n")
	b.WriteString("// fails when this file has drifted from it.\n")
	b.WriteString("//\n")
	b.WriteString("// Go owns this vocabulary so that one table serves both searches: the step\n")
	b.WriteString("// palette here, and the server-side search behind search_drops and the MCP\n")
	b.WriteString("// list_drops tool.\n\n")

	keys := make([]string, 0, len(svsearch.Aliases))
	for k := range svsearch.Aliases {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	b.WriteString("export const SV_ALIASES: Record<string, string[]> = {\n")
	for _, k := range keys {
		terms := svsearch.Aliases[k]
		quoted := make([]string, 0, len(terms))
		for _, t := range terms {
			quoted = append(quoted, tsString(t))
		}
		b.WriteString(fmt.Sprintf("  %s: [%s],\n", tsKey(k), strings.Join(quoted, ", ")))
	}
	b.WriteString("};\n\n")

	b.WriteString("export const SV_ENDINGS: string[] = [\n")
	for _, e := range svsearch.Endings {
		b.WriteString("  " + tsString(e) + ",\n")
	}
	b.WriteString("];\n\n")

	b.WriteString(fmt.Sprintf("export const ALIAS_WEIGHT = %g;\n", svsearch.AliasWeight))
	b.WriteString(fmt.Sprintf("export const MAX_TERMS = %d;\n", svsearch.MaxTerms))

	if _, err := os.Stdout.WriteString(b.String()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// tsKey quotes a key only when it has to be — a bare identifier reads better
// and matches how the table was written by hand.
func tsKey(k string) string {
	// A JS identifier admits any Unicode letter, so "beräkna" and "flöde" stay
	// bare. Quoting them instead produced a file prettier wanted to rewrite,
	// and a reformatted generated file fails the drift check.
	bare := k != ""
	for i, r := range k {
		ok := r == '_' || r == '$' || unicode.IsLetter(r) ||
			(i > 0 && unicode.IsDigit(r))
		if !ok {
			bare = false
			break
		}
	}
	if bare {
		return k
	}
	return tsString(k)
}

func tsString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}
