// SPDX-FileCopyrightText: 2026 Angels' Ware
// SPDX-License-Identifier: AGPL-3.0-or-later

package webapi

import (
	"bytes"
	"encoding/json"
	"sort"
)

// Re-importing a changed spec, as a diff rather than a replace.
//
// This is the half of the importer that protects saved flows. A spec is
// regenerated by whatever framework serves it, and an operation can vanish because
// someone deleted a handler last Tuesday. A refresh that simply replaced the
// operations would take the corresponding steps out of every flow silently — a
// step id that no longer resolves is not an error until the flow next runs.
//
// So a refresh reports what would change and requires the REMOVALS to be
// confirmed: an id is an identity, and losing one is not an edit. It is worse than
// MCPServer's rename rule, which is why it is a confirmation rather than a note —
// an org controls when it renames its own tool, and does not control when its
// vendor regenerates a spec.

type OperationChange string

const (
	OpAdded     OperationChange = "added"
	OpChanged   OperationChange = "changed"
	OpRemoved   OperationChange = "removed"
	OpUnchanged OperationChange = "unchanged"
)

type OperationDiff struct {
	ID     string          `json:"id"`
	Change OperationChange `json:"change"`
	Title  string          `json:"title,omitempty"`
	Method string          `json:"method,omitempty"`
	Path   string          `json:"path,omitempty"`
	StepID string          `json:"step_id,omitempty"`
}

type RefreshDiff struct {
	Operations []OperationDiff `json:"operations"`
	Added      int             `json:"added"`
	Changed    int             `json:"changed"`
	Removed    int             `json:"removed"`
	Unchanged  int             `json:"unchanged"`
}

func (d RefreshDiff) HasRemovals() bool { return d.Removed > 0 }

func (d RefreshDiff) RemovedStepIDs() []string {
	out := make([]string, 0, d.Removed)
	for _, op := range d.Operations {
		if op.Change == OpRemoved {
			out = append(out, op.StepID)
		}
	}
	return out
}

// DiffOperations matches on ID and nothing else, deliberately: the id is what a
// flow references, so an operation whose path moved is CHANGED (flows keep
// working) while one whose operationId was edited is a removal and an addition
// (flows do not) — which is exactly what the admin needs told rather than shielded
// from. catalogName only renders step ids in the report.
func DiffOperations(catalogName string, stored, incoming []Operation) RefreshDiff {
	byID := make(map[string]Operation, len(stored))
	for _, op := range stored {
		byID[op.ID] = op
	}
	incomingByID := make(map[string]Operation, len(incoming))
	for _, op := range incoming {
		incomingByID[op.ID] = op
	}

	var diff RefreshDiff
	for _, op := range incoming {
		prev, existed := byID[op.ID]
		switch {
		case !existed:
			diff.Added++
			diff.Operations = append(diff.Operations, OperationDiff{
				ID: op.ID, Change: OpAdded, Title: op.DisplayName(),
				Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
			})
		case sameOperation(prev, op):
			diff.Unchanged++
			diff.Operations = append(diff.Operations, OperationDiff{
				ID: op.ID, Change: OpUnchanged, Title: op.DisplayName(),
				Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
			})
		default:
			diff.Changed++
			diff.Operations = append(diff.Operations, OperationDiff{
				ID: op.ID, Change: OpChanged, Title: op.DisplayName(),
				Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
			})
		}
	}
	for _, op := range stored {
		if _, still := incomingByID[op.ID]; still {
			continue
		}
		diff.Removed++
		diff.Operations = append(diff.Operations, OperationDiff{
			ID: op.ID, Change: OpRemoved, Title: op.DisplayName(),
			Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
		})
	}
	return diff
}

// sameOperation compares the MARSHALLED form rather than field by field, so a
// field added to Operation later is covered without anyone remembering to extend
// this. A hand-written comparison is the kind that silently stops noticing a new
// field, and the failure mode is a refresh reporting "unchanged" about an
// operation that changed.
func sameOperation(a, b Operation) bool {
	// Argument order is not stable across spec regenerations but IS meaningful
	// downstream, ports being addressed by position. So it is normalised for the
	// comparison and left alone in the data: a reordering is not a change worth
	// confirming.
	return bytes.Equal(canonicalOperation(a), canonicalOperation(b))
}

func canonicalOperation(op Operation) []byte {
	sorted := append([]Arg(nil), op.Args...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	op.Args = sorted
	raw, err := json.Marshal(op)
	if err != nil {
		// Operation is plain data, so this cannot fail. Returning nil would make two
		// unmarshalable operations compare equal; the id keeps them apart.
		return []byte(op.ID)
	}
	return raw
}
