// SPDX-FileCopyrightText: 2026 Angels' Ware
// SPDX-License-Identifier: AGPL-3.0-or-later

package webapi

import (
	"bytes"
	"encoding/json"
	"sort"
)

// Re-importing a changed spec, as a diff rather than a replace.
//
// This is the half of the importer that protects saved flows. A spec is
// regenerated by whatever framework serves it, on a schedule its author does
// not control, and an operation can vanish from it because someone deleted a
// handler last Tuesday. A refresh that simply replaced the catalog's operations
// would take the corresponding steps out of every flow that referenced them —
// silently, because a step id that no longer resolves is not an error until the
// flow next runs.
//
// So a refresh reports what would change and requires the REMOVALS to be
// confirmed. The rule is the one MCPServer already applies to renaming
// (daemon/mcpservers.go): an id is an identity, and losing one is not an edit.
// It is one level worse here, which is why it is a confirmation rather than a
// note: an org controls when it renames its own MCP tool, and does not control
// when its vendor regenerates a spec.

// OperationChange is what a refresh would do to one operation.
type OperationChange string

const (
	// OpAdded is in the new spec and not in the catalog. Safe: nothing
	// references it yet.
	OpAdded OperationChange = "added"
	// OpChanged is in both, with a different shape — a new argument, a changed
	// path, a summary rewritten. The step id survives, so flows keep resolving.
	OpChanged OperationChange = "changed"
	// OpRemoved is in the catalog and NOT in the new spec. This is the one that
	// costs something: every flow referencing its step id stops resolving.
	OpRemoved OperationChange = "removed"
	// OpUnchanged is in both and identical. Reported so a refresh can say "40
	// unchanged" rather than leaving the reader to subtract.
	OpUnchanged OperationChange = "unchanged"
)

// OperationDiff is one line of a refresh report.
type OperationDiff struct {
	ID     string          `json:"id"`
	Change OperationChange `json:"change"`
	// Title is what to call it in the report: the incoming operation's name for
	// anything still present, the stored one's for a removal.
	Title string `json:"title,omitempty"`
	// Method and Path locate it for a reader deciding whether a removal matters.
	Method string `json:"method,omitempty"`
	Path   string `json:"path,omitempty"`
	// StepID is the id flows reference. Present on removals above all, because
	// it is the thing a reader needs to search their flows for.
	StepID string `json:"step_id,omitempty"`
}

// RefreshDiff is the whole report.
type RefreshDiff struct {
	Operations []OperationDiff `json:"operations"`
	Added      int             `json:"added"`
	Changed    int             `json:"changed"`
	Removed    int             `json:"removed"`
	Unchanged  int             `json:"unchanged"`
}

// HasRemovals reports whether applying this refresh would take away an
// operation. The one question the admin has to answer before it is applied.
func (d RefreshDiff) HasRemovals() bool { return d.Removed > 0 }

// RemovedStepIDs lists the step ids a refresh would stop resolving, so the
// confirmation names them rather than saying "3 removals".
func (d RefreshDiff) RemovedStepIDs() []string {
	out := make([]string, 0, d.Removed)
	for _, op := range d.Operations {
		if op.Change == OpRemoved {
			out = append(out, op.StepID)
		}
	}
	return out
}

// DiffOperations compares a catalog's stored operations with what a spec now
// offers, matched on operation id.
//
// Matched on ID and nothing else, deliberately. The id is what a flow
// references, so it is the only identity that matters here: an operation whose
// path moved is CHANGED (flows keep working), while one whose operationId was
// edited is a removal and an addition (flows do not), which is exactly what the
// admin needs to be told rather than shielded from.
//
// catalogName is only used to render step ids in the report.
func DiffOperations(catalogName string, stored, incoming []Operation) RefreshDiff {
	byID := make(map[string]Operation, len(stored))
	for _, op := range stored {
		byID[op.ID] = op
	}
	incomingByID := make(map[string]Operation, len(incoming))
	for _, op := range incoming {
		incomingByID[op.ID] = op
	}

	var diff RefreshDiff
	for _, op := range incoming {
		prev, existed := byID[op.ID]
		switch {
		case !existed:
			diff.Added++
			diff.Operations = append(diff.Operations, OperationDiff{
				ID: op.ID, Change: OpAdded, Title: op.DisplayName(),
				Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
			})
		case sameOperation(prev, op):
			diff.Unchanged++
			diff.Operations = append(diff.Operations, OperationDiff{
				ID: op.ID, Change: OpUnchanged, Title: op.DisplayName(),
				Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
			})
		default:
			diff.Changed++
			diff.Operations = append(diff.Operations, OperationDiff{
				ID: op.ID, Change: OpChanged, Title: op.DisplayName(),
				Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
			})
		}
	}
	// Removals last and in stored order, so the report reads as "here is what
	// you gain, then here is what you lose".
	for _, op := range stored {
		if _, still := incomingByID[op.ID]; still {
			continue
		}
		diff.Removed++
		diff.Operations = append(diff.Operations, OperationDiff{
			ID: op.ID, Change: OpRemoved, Title: op.DisplayName(),
			Method: op.Method, Path: op.Path, StepID: StepID(catalogName, op.ID),
		})
	}
	return diff
}

// sameOperation reports whether two operations would synthesize the same step.
//
// Compared on the MARSHALLED form rather than field by field, so a field added
// to Operation later is covered without anyone remembering to extend this. The
// alternative — a hand-written comparison — is the kind that silently stops
// noticing a new field, and the failure mode is a refresh reporting "unchanged"
// about an operation that changed.
func sameOperation(a, b Operation) bool {
	// Argument order is not meaningful to a reader and is not stable across
	// spec regenerations, but it IS meaningful downstream: ports are addressed
	// by position on the canvas. So order is normalised for the comparison and
	// left alone in the data — a reordering is not a change worth confirming,
	// and schemaports.Build re-sorts deterministically anyway.
	return bytes.Equal(canonicalOperation(a), canonicalOperation(b))
}

func canonicalOperation(op Operation) []byte {
	sorted := append([]Arg(nil), op.Args...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	op.Args = sorted
	raw, err := json.Marshal(op)
	if err != nil {
		// Operation is plain data with no custom marshaller, so this cannot
		// fail. Returning nil would make two unmarshalable operations compare
		// equal; the id keeps them apart.
		return []byte(op.ID)
	}
	return raw
}

// ApplyRefresh produces the operation list a confirmed refresh would store.
//
// Additions and changes are taken from the spec. Removals are taken only when
// confirmed; without confirmation the stored operation is KEPT, so a refresh
// that the admin has not signed off cannot cost a flow its steps. That makes
// the unconfirmed path strictly additive, which is the safe default for
// something a vendor's build pipeline can trigger.
func ApplyRefresh(stored, incoming []Operation, confirmRemovals bool) []Operation {
	incomingByID := make(map[string]Operation, len(incoming))
	for _, op := range incoming {
		incomingByID[op.ID] = op
	}
	out := make([]Operation, 0, len(incoming)+len(stored))
	seen := map[string]bool{}
	for _, op := range incoming {
		out = append(out, op)
		seen[op.ID] = true
	}
	if confirmRemovals {
		return out
	}
	// Kept in stored order after the incoming ones, so a catalog that is never
	// refreshed-with-removals does not reshuffle on every import.
	for _, op := range stored {
		if seen[op.ID] {
			continue
		}
		out = append(out, op)
	}
	return out
}
